server:
  port: 8999
spring:
  application:
    name: eureka-registry
eureka:
  instance:
    hostname: eureka-peer1
  client:
    serviceUrl:
      defaultZone: http://eureka-peer2:8998/eureka/
    register-with-eureka: true
