server:
  port: 9888
spring:
  rabbitmq:
    addresses: 10.1.11.32:5672,10.1.11.32:5672
    username: kld_web
    password: 123456
    virtual-host: web
  cloud:
    bus:
      refresh:
        enabled: true
      trace:
        enabled: true
management:
  security:
    enabled: false
#  context-path: config
